# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-20 14:53
from __future__ import unicode_literals

import core.models
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and -/./_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.-]+$', 'Enter a valid username. This value may contain only letters, numbers and -/./_ characters.', 'invalid')], verbose_name='username')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='email address')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('foods', django.contrib.postgres.fields.jsonb.JSONField(default='')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('type_of_food', models.CharField(choices=[('T', 'Traditional'), ('F', 'Fast Food'), ('B', 'Traditional and Fast Food')], max_length=1)),
                ('phone_numbers', models.CharField(max_length=11)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', core.models.MemberManager()),
            ],
        ),
    ]
